name: publish

on:
  push:
    branches: [ master ]

  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch: # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # otherwise you will fail to push refs to dest repo

    - name: Cache conda
      uses: actions/cache@v2
      env:
        CACHE_NUMBER: 0 # increase to reset cache if env file has not changed
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.lock') }}

    - name: Setup environment
      uses: conda-incubator/setup-miniconda@v2
      with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          environment-file: environment.lock
          activate-environment: covid-19
          use-mamba: true
          use-only-tar-bz2: true # required for cache to work

    - name: Make index.html
      run: jupyter nbconvert daily_update.ipynb --execute

    - name: Make ar/index.html
      run: cd ar/ && jupyter nbconvert daily_update_ar.ipynb --execute

    - name: Make ar/vacunas/index.html
      run: cd ar/vacunas && jupyter nbconvert vacunas_ar.ipynb --execute

    - name: Create site
      run: |
        mkdir -p public/ar/vacunas
        mv index.html public
        mv ar/index.html public/ar
        mv ar/vacunas/index.html public/ar/vacunas

    - name: Deploy site
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        force_orphan: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
