name: publish

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Create environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment.yml
        activate-environment: covid-19
        channels: conda-forge, defaults
        mamba-version: "*"

    - name: Make index.html
      shell: bash -l {0}
      run: jupyter nbconvert daily_update.ipynb --execute

    - name: Make ar/index.html
      shell: bash -l {0}
      run: cd ar/ && jupyter nbconvert daily_update.ipynb --execute

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.html ar/index.html
        git commit -m "Commit changes (do not push)" -a

        git checkout gh-pages
        git checkout master -- index.html ar/index.html
        git add index.html ar/index.html
        git commit -m "Commit changes (automatic)" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
