name: publish

on:
  push:
    branches: [ master ]

  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch: # manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # otherwise you will fail to push refs to dest repo

    - name: Cache conda
      uses: actions/cache@v2
      env:
        CACHE_NUMBER: 0 # increase to reset cache if env file has not changed
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.lock') }}

    - name: Setup environment
      uses: conda-incubator/setup-miniconda@v2
      with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          environment-file: environment.lock
          activate-environment: covid-19
          use-mamba: true
          use-only-tar-bz2: true # required for cache to work

    - name: Make index.html
      run: jupyter nbconvert daily_update.ipynb --execute

    - name: Make ar/index.html
      run: cd ar/ && jupyter nbconvert daily_update.ipynb --execute

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.html ar/index.html
        git commit -m "Commit changes (do not push)" -a

        git checkout gh-pages
        git checkout master -- index.html ar/index.html
        git add index.html ar/index.html
        git commit -m "Commit changes (automatic)" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
